export const brand = {
  colors: {
    navy: '#0A1628',
    navyLight: '#132240',
    navyLighter: '#1a3058',
    accent: '#3B82F6',
    accentLight: '#60A5FA',
    accentHover: '#2563EB',
    catGen: '#F59E0B',
    catConn: '#3B82F6',
    catNetwork: '#64748B',
    catLoad: '#10B981',
    symBlue: '#185FA5',
    symBlueLight: '#E6F1FB',
    symBlueDark: '#0C447C',
    symAmber: '#854F0B',
    symAmberLight: '#FAEEDA',
    symAmberDark: '#412402',
    symGray: '#B4B2A9',
    symGrayLight: '#F1EFE8',
    symGrayDark: '#2C2C2A',
    surface: '#f8fafc',
    textPrimary: '#0f172a',
    textDark: '#f1f5f9',
    white: '#ffffff',
  },
  typography: {
    fontFamily: '"Inter", system-ui, -apple-system, sans-serif',
    heading: {
      '4xl': 'text-4xl font-bold tracking-tight',
      '3xl': 'text-3xl font-bold tracking-tight',
      '2xl': 'text-2xl font-bold tracking-tight',
      xl: 'text-xl font-semibold tracking-tight',
      lg: 'text-lg font-semibold',
    },
    body: {
      lg: 'text-lg',
      base: 'text-base',
      sm: 'text-sm',
    },
  },
  spacing: {
    sectionPadding: 'py-20',
    cardPadding: 'p-6',
  },
  cardStyles: {
    base: 'rounded-2xl border border-white/10 transition-all duration-300',
    hover: 'hover:shadow-lg hover:border-white/20',
    darkBg: 'bg-navy-light',
    lightBg: 'bg-white',
  },
  buttonStyles: {
    primary: 'rounded-full bg-accent text-white px-6 py-2.5 font-medium hover:bg-accent-hover transition-colors',
    secondary: 'rounded-full border border-accent text-accent px-6 py-2.5 font-medium hover:bg-accent/10 transition-colors',
    ghost: 'rounded-full text-gray-400 px-4 py-2 hover:text-white hover:bg-white/5 transition-colors',
    danger: 'rounded-full bg-red-600 text-white px-6 py-2.5 font-medium hover:bg-red-700 transition-colors',
  },
  categories: [
    'Introduction',
    'Value Chain',
    'Products',
    'Partnerships',
    'Team',
    'Company',
    'Custom',
  ] as const,
} as const

export type Category = (typeof brand.categories)[number]
